### ISSUE TITLE
Failed to install oh-my-github to Windows10/32-bit

### ISSUE THREAD

**Issue by withsmilo** [oh-my-github/generator#20]
## Steps
1. Download and install git
   - https://git-scm.com/download/win
2. Download and install python 2.7.11
   - https://www.python.org/downloads/
3. Follow instructions on http://1ambda.github.io/create-github-profile-in-10-minutes
   - Prerequisites
   - Install: Viewer
4. Download and install nvm-windows v1.1.0
   - https://github.com/coreybutler/nvm-windows/releases
   - Change installing path from `C:\Users\테스트\AppData\Roaming\nvm` to `C:\nvm` because nvm cannot recognize unicode path.
5. Execute cmd as administrator
6. Install and set nodejs 5.0.0
   - `> nvm install 5.0.0` (`> nvm install 5.0.0 32` if you use Windows 32-bit version)
   - `> nvm use 5.0.0` (`> nvm use 5.0.0 32` if you use Windows 32-bit version)
7. Install oh-my-github
   - `> npm install oh-my-github -g`
   - Occurred below ERROR!

```
npm WARN install Couldn't install optional dependency: Unsupported
C:\Program Files\nodejs\omg -> C:\Program Files\nodejs\node_modules\oh-my-github\bin\omg
> bufferutil@1.2.1 install C:\Program Files\nodejs\node_modules\oh-my-github\node_modules\bufferutil
> node-gyp rebuild
C:\Program Files\nodejs\node_modules\oh-my-github\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\nvm\v5.0.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
이 솔루션의 프로젝트를 한 번에 하나씩 빌드합니다. 병렬 빌드를 사용하려면 "/m" 스위치를 추가하십시오.
MSBUILD : error MSB4132: 도구 버전 "2.0"을(를) 인식할 수 없습니다. 사용할 수 있는 도구 버전은 "4.0"입니다.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nvm\v5.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\nvm\\v5.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\oh-my-github\node_modules\bufferutil
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oh-my-github" "-g"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
```
### May be...

node-gyp also need other installation(Visual Studio?), referred from https://github.com/nodejs/node-gyp#installation. I will update this issue later.

**Comment by 1ambda** [comment]
Thanks you for the reporting. I will add node-gyp installation guide on Windows platform to `README.md`

**Comment by 1ambda** [comment]
https://github.com/oh-my-github/oh-my-github/commit/d84aa60149b7e45412f85dceaa5efd47ce0fddef
